// -*- mode: C++; c-file-style: "cc-mode" -*-
//=============================================================================
//
// Code available from: https://verilator.org
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of either the GNU Lesser General Public License Version 3
// or the Perl Artistic License Version 2.0.
// SPDX-FileCopyrightText: 2001-2026 Wilson Snyder
// SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
//
//=============================================================================
///
/// \file
/// \brief Verilated C++ tracing in VTR format implementation code
///
/// This file must be compiled and linked against all Verilated objects
/// that use --trace-vtr, together with the VTR C library (libvtr, header
/// vtr.h). Point VTR_INCLUDE and VTR_LIBDIR at them when running make.
///
/// Use "verilator --trace-vtr" to add this to the Makefile for the linker.
///
//=============================================================================

// clang-format off

#include "verilated.h"
#include "verilated_vtr_c.h"

#include "vtr.h"

#include <cmath>
#include <sstream>
#include <string>

// clang-format on

//=============================================================================
// Specialization of the generics for this trace format

#define VL_SUB_T VerilatedVtr
#define VL_BUF_T VerilatedVtrBuffer
#include "verilated_trace_imp.h"
#undef VL_SUB_T
#undef VL_BUF_T

//=============================================================================
// VerilatedVtr

VerilatedVtr::VerilatedVtr(void* /*vtr*/) {}

VerilatedVtr::~VerilatedVtr() {
    if (m_vtr) vtr_writer_close(m_vtr);
    if (m_signalp) VL_DO_CLEAR(delete[] m_signalp, m_signalp = nullptr);
}

void VerilatedVtr::open(const char* filename) VL_MT_SAFE_EXCLUDES(m_mutex) {
    const VerilatedLockGuard lock{m_mutex};
    vtr_writer_options opts;
    vtr_writer_options_default(&opts);
    // Verilator only hands over values that differ from the previous dump,
    // so the writer's own comparison would be redundant work.
    opts.dedup = 0;
    m_vtr = vtr_writer_create(filename, &opts);
    if (!m_vtr) {
        VL_PRINTF_MT("%%Error: VTR trace open failed: %s: %s\n", filename, vtr_last_error());
        return;
    }
    // timeRes() is 10^exp seconds; FST time units are the same power of ten.
    vtr_writer_set_timescale(m_vtr, static_cast<int8_t>(std::lround(std::log10(timeRes()))));
    vtr_writer_set_writer_name(m_vtr, "Generated by VerilatedVtr");
    vtr_writer_set_file_type(m_vtr, 0);  // Verilog
    constDump(true);  // First dump must contain the const signals
    fullDump(true);  // First dump must be full for VTR

    Super::traceInit();

    // convert m_code2signal into an array for fast lookup
    if (!m_signalp) {
        m_signalp = new uint32_t[nextCode()]{0};
        for (const auto& i : m_code2signal) m_signalp[i.first] = i.second;
    }
    m_code2signal.clear();
}

void VerilatedVtr::close() VL_MT_SAFE_EXCLUDES(m_mutex) {
    const VerilatedLockGuard lock{m_mutex};
    Super::closeBase();
    emitTimeChangeMaybe();
    if (m_vtr && vtr_writer_close(m_vtr) != VTR_OK) {
        VL_PRINTF_MT("%%Error: VTR trace close failed: %s\n", vtr_last_error());
    }
    m_vtr = nullptr;
}

void VerilatedVtr::flush() VL_MT_SAFE_EXCLUDES(m_mutex) {
    const VerilatedLockGuard lock{m_mutex};
    Super::flushBase();
    emitTimeChangeMaybe();
    if (m_vtr) vtr_writer_flush(m_vtr);
}

void VerilatedVtr::emitTimeChange(uint64_t timeui) {
    if (!timeui) vtr_writer_set_time(m_vtr, timeui);
    m_timeui = timeui;
}

VL_ATTR_ALWINLINE
void VerilatedVtr::emitTimeChangeMaybe() {
    if (VL_UNLIKELY(m_timeui)) {
        vtr_writer_set_time(m_vtr, m_timeui);
        m_timeui = 0;
    }
}

//=============================================================================
// Decl

void VerilatedVtr::declDTypeEnum(int dtypenum, const char* name, uint32_t elements,
                                 unsigned int /*minValbits*/, const char** itemNamesp,
                                 const char** itemValuesp) {
    const uint32_t node = vtr_writer_add_enum_table(m_vtr, name, elements, itemNamesp, itemValuesp);
    const bool newEntry = m_local2vtrEnum[initUserp()].emplace(dtypenum, node).second;
    assert(newEntry);
}

void VerilatedVtr::pushPrefix(const char* namep, VerilatedTracePrefixType type, int left,
                              int right) {
    assert(!m_prefixStack.empty());  // Constructor makes an empty entry
    const std::string name{namep};
    // An empty name means this is the root of a model created with
    // name()=="".  The tools get upset if we try to pass this as empty, so
    // we put the signals under a new $rootio scope, but the signals
    // further down will be peers, not children (as usual for name()!="").
    const std::string prevPrefix = m_prefixStack.back().first;
    if (name == "$rootio" && !prevPrefix.empty()) {
        // Upper has name, we can suppress inserting $rootio, but still push so popPrefix works
        m_prefixStack.emplace_back(prevPrefix, VerilatedTracePrefixType::ROOTIO_WRAPPER);
        return;
    }
    if (name.empty()) {
        m_prefixStack.emplace_back(prevPrefix, VerilatedTracePrefixType::ROOTIO_WRAPPER);
        return;
    }

    bool isProperScope = true;
    switch (type) {
    case VerilatedTracePrefixType::ARRAY_PACKED:
    case VerilatedTracePrefixType::ARRAY_UNPACKED: isProperScope = false; break;
    default: break;
    }

    // This code assumes a signal at a given prefix level is declared before
    // any pushPrefix are done at that same level.
    const std::string newPrefix = prevPrefix + name;
    m_prefixStack.emplace_back(newPrefix + (isProperScope ? " " : ""), type);

    // Scope type codes are the FST ones (VTR reuses them): 0 module, 6 struct,
    // 7 union, 9 interface, 22 SystemVerilog array.
    uint16_t scopeType = 0;
    switch (type) {
    case VerilatedTracePrefixType::SCOPE_MODULE: scopeType = 0; break;
    case VerilatedTracePrefixType::SCOPE_INTERFACE: scopeType = 9; break;
    case VerilatedTracePrefixType::STRUCT_PACKED:
    case VerilatedTracePrefixType::STRUCT_UNPACKED: scopeType = 6; break;
    case VerilatedTracePrefixType::UNION_PACKED: scopeType = 7; break;
    case VerilatedTracePrefixType::ARRAY_PACKED:
    case VerilatedTracePrefixType::ARRAY_UNPACKED: scopeType = 22; break;
    default: break;
    }
    const uint32_t node = vtr_writer_begin_scope(m_vtr, namep, scopeType, nullptr);
    switch (type) {
    case VerilatedTracePrefixType::STRUCT_PACKED:
    case VerilatedTracePrefixType::UNION_PACKED:
    case VerilatedTracePrefixType::ARRAY_PACKED: {
        vtr_value v{};
        v.tag = VTR_VAL_BOOL;
        v.b = 1;
        vtr_writer_node_attr(m_vtr, node, "packed", &v);
        break;
    }
    default: break;
    }
    if (type == VerilatedTracePrefixType::ARRAY_PACKED
        || type == VerilatedTracePrefixType::ARRAY_UNPACKED) {
        vtr_value v{};
        v.tag = VTR_VAL_I64;
        v.i = left;
        vtr_writer_node_attr(m_vtr, node, "left", &v);
        v.i = right;
        vtr_writer_node_attr(m_vtr, node, "right", &v);
    }
}

void VerilatedVtr::popPrefix() {
    assert(!m_prefixStack.empty());
    if (m_prefixStack.back().second != VerilatedTracePrefixType::ROOTIO_WRAPPER) {
        vtr_writer_end_scope(m_vtr);
    }
    m_prefixStack.pop_back();
    assert(!m_prefixStack.empty());  // Always one left, the constructor's initial one
}

void VerilatedVtr::declare(uint32_t code, const char* name, int dtypenum,
                           VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                           VerilatedTraceSigType type, bool array, int arraynum, bool bussed,
                           int msb, int lsb) {
    const int bits = ((msb > lsb) ? (msb - lsb) : (lsb - msb)) + 1;

    const std::string hierarchicalName = m_prefixStack.back().first + name;

    const bool enabled = Super::declCode(code, hierarchicalName, bits);
    if (!enabled) return;

    // Same naming as the FST backend: "name[index]" for array members and a
    // trailing " [msb:lsb]" for buses, so files of both formats read alike.
    assert(hierarchicalName.rfind(' ') != std::string::npos);
    std::stringstream name_ss;
    name_ss << lastWord(hierarchicalName);
    if (array) name_ss << "[" << arraynum << "]";
    if (bussed) name_ss << " [" << msb << ":" << lsb << "]";
    const std::string name_str = name_ss.str();

    uint8_t varDir = 0;  // implicit
    switch (direction) {
    case VerilatedTraceSigDirection::INOUT: varDir = 3; break;
    case VerilatedTraceSigDirection::OUTPUT: varDir = 2; break;
    case VerilatedTraceSigDirection::INPUT: varDir = 1; break;
    case VerilatedTraceSigDirection::NONE: varDir = 0; break;
    }

    // Var type codes are the FST ones (VTR reuses them).
    uint16_t varType;
    // Doubles have special decoding properties, so must indicate if a double
    if (type == VerilatedTraceSigType::DOUBLE) {
        if (kind == VerilatedTraceSigKind::PARAMETER) {
            varType = 4;  // real_parameter
        } else {
            varType = 3;  // real
        }
    }
    // clang-format off
    else if (kind == VerilatedTraceSigKind::PARAMETER) varType = 2;
    else if (kind == VerilatedTraceSigKind::SUPPLY0) varType = 6;
    else if (kind == VerilatedTraceSigKind::SUPPLY1) varType = 7;
    else if (kind == VerilatedTraceSigKind::TRI) varType = 9;
    else if (kind == VerilatedTraceSigKind::TRI0) varType = 13;
    else if (kind == VerilatedTraceSigKind::TRI1) varType = 14;
    else if (kind == VerilatedTraceSigKind::TRIAND) varType = 10;
    else if (kind == VerilatedTraceSigKind::TRIOR) varType = 11;
    else if (kind == VerilatedTraceSigKind::TRIREG) varType = 12;
    else if (kind == VerilatedTraceSigKind::WIRE) varType = 16;
    //
    else if (type == VerilatedTraceSigType::INTEGER) varType = 1;
    else if (type == VerilatedTraceSigType::BIT) varType = 22;
    else if (type == VerilatedTraceSigType::LOGIC) varType = 23;
    else if (type == VerilatedTraceSigType::INT) varType = 24;
    else if (type == VerilatedTraceSigType::SHORTINT) varType = 25;
    else if (type == VerilatedTraceSigType::LONGINT) varType = 26;
    else if (type == VerilatedTraceSigType::BYTE) varType = 27;
    else if (type == VerilatedTraceSigType::EVENT) varType = 0;
    else if (type == VerilatedTraceSigType::TIME) varType = 8;
    else { assert(0); /* Unreachable */ }
    // clang-format on

    uint32_t node = VTR_NONE;
    const auto it = vlstd::as_const(m_code2signal).find(code);
    if (it == m_code2signal.end()) {  // New
        const uint8_t sigKind = (type == VerilatedTraceSigType::DOUBLE) ? 1 : 0;
        uint32_t signal = VTR_NONE;
        // Verilated models are two-state.
        vtr_writer_add_var(m_vtr, name_str.c_str(), varType, varDir, sigKind,
                           static_cast<uint32_t>(bits), 2, &node, &signal);
        m_code2signal[code] = signal;
    } else {  // Alias
        vtr_writer_add_alias(m_vtr, name_str.c_str(), varType, varDir, it->second, &node);
    }

    if (dtypenum > 0) {
        vtr_value v{};
        v.tag = VTR_VAL_U64;
        v.u = m_local2vtrEnum.at(initUserp()).at(dtypenum);
        vtr_writer_node_attr(m_vtr, node, "enum_table", &v);
    }
}

// versions to call when the sig is not array member
void VerilatedVtr::declEvent(uint32_t code, const char* name, int dtypenum,
                             VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                             VerilatedTraceSigType type) {
    declare(code, name, dtypenum, direction, kind, type, false, -1, false, 0, 0);
}
void VerilatedVtr::declBit(uint32_t code, const char* name, int dtypenum,
                           VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                           VerilatedTraceSigType type) {
    declare(code, name, dtypenum, direction, kind, type, false, -1, false, 0, 0);
}
void VerilatedVtr::declBus(uint32_t code, const char* name, int dtypenum,
                           VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                           VerilatedTraceSigType type, int msb, int lsb) {
    declare(code, name, dtypenum, direction, kind, type, false, -1, true, msb, lsb);
}
void VerilatedVtr::declQuad(uint32_t code, const char* name, int dtypenum,
                            VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                            VerilatedTraceSigType type, int msb, int lsb) {
    declare(code, name, dtypenum, direction, kind, type, false, -1, true, msb, lsb);
}
void VerilatedVtr::declWide(uint32_t code, const char* name, int dtypenum,
                            VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                            VerilatedTraceSigType type, int msb, int lsb) {
    declare(code, name, dtypenum, direction, kind, type, false, -1, true, msb, lsb);
}
void VerilatedVtr::declDouble(uint32_t code, const char* name, int dtypenum,
                              VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                              VerilatedTraceSigType type) {
    declare(code, name, dtypenum, direction, kind, type, false, -1, false, 63, 0);
}

// versions to call when the sig is array member
void VerilatedVtr::declEventArray(uint32_t code, const char* name, int dtypenum,
                                  VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                                  VerilatedTraceSigType type, int arraynum) {
    declare(code, name, dtypenum, direction, kind, type, true, arraynum, false, 0, 0);
}
void VerilatedVtr::declBitArray(uint32_t code, const char* name, int dtypenum,
                                VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                                VerilatedTraceSigType type, int arraynum) {
    declare(code, name, dtypenum, direction, kind, type, true, arraynum, false, 0, 0);
}
void VerilatedVtr::declBusArray(uint32_t code, const char* name, int dtypenum,
                                VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                                VerilatedTraceSigType type, int arraynum, int msb, int lsb) {
    declare(code, name, dtypenum, direction, kind, type, true, arraynum, true, msb, lsb);
}
void VerilatedVtr::declQuadArray(uint32_t code, const char* name, int dtypenum,
                                 VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                                 VerilatedTraceSigType type, int arraynum, int msb, int lsb) {
    declare(code, name, dtypenum, direction, kind, type, true, arraynum, true, msb, lsb);
}
void VerilatedVtr::declWideArray(uint32_t code, const char* name, int dtypenum,
                                 VerilatedTraceSigDirection direction, VerilatedTraceSigKind kind,
                                 VerilatedTraceSigType type, int arraynum, int msb, int lsb) {
    declare(code, name, dtypenum, direction, kind, type, true, arraynum, true, msb, lsb);
}
void VerilatedVtr::declDoubleArray(uint32_t code, const char* name, int dtypenum,
                                   VerilatedTraceSigDirection direction,
                                   VerilatedTraceSigKind kind, VerilatedTraceSigType type,
                                   int arraynum) {
    declare(code, name, dtypenum, direction, kind, type, true, arraynum, false, 63, 0);
}
//=============================================================================
// Get/commit trace buffer

VerilatedVtr::Buffer* VerilatedVtr::getTraceBuffer(uint32_t /*fidx*/) { return new Buffer{*this}; }

void VerilatedVtr::commitTraceBuffer(VerilatedVtr::Buffer* bufp) { delete bufp; }

//=============================================================================
// VerilatedVtrBuffer implementation

//=============================================================================
// Trace rendering primitives

// Note: emit* are only ever called from one place (full* in
// verilated_trace_imp.h, which is included in this file at the top),
// so always inline them.

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitEvent(uint32_t code) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_bit(m_vtr, m_signalp[code], 1);
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitBit(uint32_t code, CData newval) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_bit(m_vtr, m_signalp[code], newval ? 1 : 0);
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitCData(uint32_t code, CData newval, int /*bits*/) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_u64(m_vtr, m_signalp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitSData(uint32_t code, SData newval, int /*bits*/) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_u64(m_vtr, m_signalp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitIData(uint32_t code, IData newval, int /*bits*/) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_u64(m_vtr, m_signalp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitQData(uint32_t code, QData newval, int /*bits*/) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_u64(m_vtr, m_signalp[code], newval);
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitWData(uint32_t code, WDataInP newvalp, int bits) {
    m_owner.emitTimeChangeMaybe();
    // WData words are little-endian 32-bit words, word 0 = bits 0..31, as VTR expects.
    vtr_writer_emit_words(m_vtr, m_signalp[code], newvalp.datap(), VL_WORDS_I(bits));
}

VL_ATTR_ALWINLINE
void VerilatedVtrBuffer::emitDouble(uint32_t code, double newval) {
    m_owner.emitTimeChangeMaybe();
    vtr_writer_emit_real(m_vtr, m_signalp[code], newval);
}
